package CookBookView.detailview;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.Pane;

public class IngredientController {
	@FXML
	private Pane ingredientPane;

	// Event Listener on Pane[#ingredientPane].onDragDetected
	@FXML
	public void showIngredients(MouseEvent event) {
		// TODO Autogenerated
	}
}
