package CookBookView.detailview;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;

public class IngredientController {
	@FXML
	private Pane ingredientPane;
	
	@FXML
	private VBox vbox; 
	
	
	// Event Listener on Pane[#ingredientPane].onDragDetected
	@FXML
	public void showIngredients(MouseEvent event) {
		// TODO Autogenerated
	}
	public VBox getVBox() {
		return this.vbox;
	}
}
