package CookBookView.searchview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.awt.Component;
import java.awt.ScrollPane;
import java.io.IOException;

import CookBookView.listview.ListViewController;
import CookBookView.listview.PaneController;
import CookBookView.loginview.loginController;
import CookBookView.registerview.registerViewController;
import javafx.event.ActionEvent;



public class SearchViewController {
	@FXML
	private TextField searcher;
	@FXML
	private Button logout;
	@FXML
	private Button blacksearch;
	@FXML
	private Button bluesearch;
	@FXML
	private Button showrecipes;
	@FXML
	private Button userRecipes;
	@FXML
	private Button favouriterecipes;
	@FXML
	private Button rankedrecipes;
	@FXML
	private Button createrecipes;
	
	private Stage stage;
	
	private Scene scene;

	
	// Event Listener on Button[#logout].onAction
	@FXML
	public void logOut(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#blacksearch].onAction
	@FXML
	public void showblue(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bluesearch].onAction
	@FXML
	public void searchRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#showrecipes].onAction
	@FXML
	public void showAllrecipes(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../listview/listview.fxml"));
		VBox root = (AnchorPane) loader.load();
		ListViewController lvc = loader.getController();
		//lvc.setStageAndScene(stage, scene);
		
		ScrollPane recipepane1 = lvc.getPane();
		
		int recipenumber =30; 
		while(recipenumber>0) {
			FXMLLoader recipeloader = new FXMLLoader(getClass().getResource("../listview/pane.fxml"));
			Pane pane = recipeloader.load();
			PaneController panecontroller = recipeloader.getController();
			recipepane1.add(vbox);
			
			
			recipenumber = recipenumber -1; 
		}
		
		
		lvc.setStage(stage);
		lvc.setScene(scene);
		
		scene.setRoot(root);
		stage.setScene(scene);
		
		stage.show();
		
		
		/** FXMLLoader loader = new FXMLLoader();  
         loader.setLocation(getClass().getResource("study.fxml"));  
         loader.load();  
         Parent root = loader.getRoot();  
         //主控制器的对象，用于获取主函数中的Stage对象  
         Controller c =(Controller)loader.getController();  
         c.setStage(primaryStage);  
           
         Scene scene = new Scene(root,1000,600);  
         primaryStage.setScene(scene);  
         primaryStage.show();  
		*/
		
		
		
		// TODO Autogenerated
	}
	// Event Listener on Button[#userRecipes].onAction
	@FXML
	public void showUserRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#favouriterecipes].onAction
	@FXML
	public void showUserFavouriteRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#rankedrecipes].onAction
	@FXML
	public void showRankedRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#createrecipes].onAction
	@FXML
	public void createNewRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public void setScene(Scene scene) {
		this.scene = scene;
	}
}
