package CookBookView.searchview;

import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class SearchViewController {
	@FXML
	private TextField searcher;
	@FXML
	private Button logout;
	@FXML
	private Button blacksearch;
	@FXML
	private Button bluesearch;
	@FXML
	private Button showrecipes;
	@FXML
	private Button userRecipes;
	@FXML
	private Button favouriterecipes;
	@FXML
	private Button rankedrecipes;
	@FXML
	private Button createrecipes;
	
	private Stage stage ;
	private Scene scene ; 
	


	// Event Listener on TextField[#searcher].onAction
	@FXML
	public void searchsomething(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#logout].onAction
	@FXML
	public void logOut(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#blacksearch].onAction
	@FXML
	public void showblue(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bluesearch].onAction
	@FXML
	public void searchRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#showrecipes].onAction
	@FXML
	public void showAllrecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#userRecipes].onAction
	@FXML
	public void showUserRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#favouriterecipes].onAction
	@FXML
	public void showUserFavouriteRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#rankedrecipes].onAction
	@FXML
	public void showRankedRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#createrecipes].onAction
	@FXML
	public void createNewRecipes(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setStage(Stage stage ) {
		this.stage = stage ;
	}
	public void setScene(Scene scene) {
		this.scene = scene;
	}
}
