package CookBookView.searchview;

import java.io.IOException;
import java.util.LinkedList;

import CookBookDataBaseAcess.DatabaselayerObject;
import CookBookEntity.Recipe;
import CookBookView.firstview.fvController;
import CookBookView.listview.ListviewController;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class SearchViewController {
	@FXML
	private TextField searcher;
	@FXML
	private Button logout;
	@FXML
	private Button blacksearch;
	@FXML
	private Button bluesearch;
	@FXML
	private Button showrecipes;
	@FXML
	private Button userRecipes;
	@FXML
	private Button favouriterecipes;
	@FXML
	private Button rankedrecipes;
	@FXML
	private Button createrecipes;
	private Stage stage;
	private Scene scene;
	private DatabaselayerObject databaselayerObject;

	// Event Listener on Button[#logout].onAction
	@FXML
	public void logOut(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../firstview/fv.fxml"));
		Parent root = loader.load();
		fvController controller = loader.getController();
		controller.setStageAndScene(stage, scene);
		scene.setRoot(root);
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#blacksearch].onMouseEntered
	@FXML
	public void showblue(MouseEvent event) {
		Image image = new Image(getClass().getResourceAsStream("æ�œç´¢-5.png"));
		blacksearch.setGraphic(new ImageView(image));
	}

	// Event Listener on Button[#blacksearch].onMouseClicked
	@FXML
	public void searchRecipes(MouseEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../listview/listview.fxml"));
		Parent root = loader.load();
		ListviewController controller = loader.getController();
		controller.setStageAndScene(stage, scene);
		controller.setDatabaselayerObject(databaselayerObject);
		controller.createSearchedRecipeSubview(searcher);
		scene.setRoot(root);
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#showrecipes].onAction
	@FXML
	public void showAllrecipes(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../listview/listview.fxml"));
		Parent root = loader.load();
		ListviewController controller = loader.getController();
		controller.setStageAndScene(stage, scene);
		controller.setDatabaselayerObject(databaselayerObject);
		controller.createAllRecipeSubView(searcher);
		scene.setRoot(root);
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#userRecipes].onAction
	@FXML
	public void showUserRecipes(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../listview/listview.fxml"));
		Parent root = loader.load();
		ListviewController controller = loader.getController();
		controller.setStageAndScene(stage, scene);
		controller.setDatabaselayerObject(databaselayerObject);
		controller.createUserRecipeSubView(searcher);
		scene.setRoot(root);
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#favouriterecipes].onAction
	@FXML
	public void showUserFavouriteRecipes(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../listview/listview.fxml"));
		Parent root = loader.load();
		ListviewController controller = loader.getController();
		controller.setStageAndScene(stage, scene);
		controller.setDatabaselayerObject(databaselayerObject);
		controller.createUserFavouriteRecipeSubView(searcher);
		scene.setRoot(root);
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#rankedrecipes].onAction
	@FXML
	public void showRankedRecipes(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#createrecipes].onAction
	@FXML
	public void createNewRecipes(ActionEvent event) {
		// TODO Autogenerated
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public void setScene(Scene scene) {
		this.scene = scene;
	}

	public void setStageAndScene(Stage stage, Scene scene) {
		this.stage = stage;
		this.scene = scene;
	}

	public void setDatabaselayerObject(DatabaselayerObject databaseLayerObject) {
		this.databaselayerObject = databaselayerObject;
	}
}
