package CookBookView.registerview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class registerViewController {
	@FXML
	private TextField username;
	@FXML
	private TextField userpassword1;
	@FXML
	private TextField userpassword2;
	@FXML
	private Button ok;

	// Event Listener on Button[#ok].onAction
	@FXML
	public void userRegister(ActionEvent event) throws IOException {
		
		//if()
		 
		GridPane root = (GridPane) FXMLLoader.load(getClass().getResource("mini2.fxml"));
        Scene scene = new Scene(root, 270, 160);
        Stage stage = new Stage();
        stage.setScene(scene);
		stage.show();
		
		
		/**
		 * if()
		 * 
		 */
		// TODO Autogenerated
	}
}
