package CookBookView.registerview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class registerViewController {
	@FXML
	private TextField username;
	@FXML
	private TextField userpassword1;
	@FXML
	private TextField userpassword2;
	@FXML
	private Button ok;

	private Stage stage;

	private Scene scene;

	// Event Listener on Button[#ok].onAction
	@FXML
	public void userRegister(ActionEvent event) throws IOException {

		// if()

		GridPane root = (GridPane) FXMLLoader.load(getClass().getResource("mini2.fxml"));
		Scene scene = new Scene(root, 270, 160);
		Stage stage = new Stage();
		stage.setScene(scene);
		stage.show();

		/**
		 * if()
		 * 
		 */
		// TODO Autogenerated
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public void setScene(Scene scene) {
		this.scene = scene;
	}

	public void setStageAndScene(Stage stage, Scene scene) {
		this.stage = stage;
		this.scene = scene;
	}
}
