package CookBookView.loginview.tinywin;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class miniController {
	@FXML
	private Text warningText;
	@FXML
	private Button register;
	@FXML
	private Button ok;

	// Event Listener on Button[#register].onAction
	@FXML
	public void registerView(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ok].onAction
	@FXML
	public void loginView(ActionEvent event) {
		// TODO Autogenerated
	}
}
