package CookBookView.loginview.tinywin;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class miniController {
	@FXML
	private Text warningText;
	@FXML
	private Button register;
	@FXML
	private Button ok;
	
	
	
	private int loginresult; 
	
	// Event Listener on Button[#register].onAction
	@FXML
	public void registerView(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ok].onAction
	@FXML
	public void loginView(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public Text getText() {
		return this.warningText;
	}
	
	public void changeText(int result) {
		System.out.println("hello");
		if(result==1) {
			this.warningText.setText("hello");
		}else {
			this.warningText.setText("not hello");
		}
	}
	public void test() {
		System.out.println("123");
	}
	
	
}
