package CookBookView.loginview.tinywin;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class miniController {
	@FXML
	private Text warningText;
	@FXML
	private Button register;
	@FXML
	private Button ok;

	private int loginresult;
	private Stage stage;
	private Scene scene;

	// Event Listener on Button[#register].onAction
	@FXML
	public void registerView(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#ok].onAction
	@FXML
	public void loginView(ActionEvent event) {
		stage.close();
	}

	public Text getText() {
		return this.warningText;
	}

	public void changeText(int result) {
		System.out.println("hello");
		if (result == -1) {
			this.warningText.setText("User name does not exist");
		} else {
			this.warningText.setText("User password is not right");
		}
	}

	public void test() {
		System.out.println("123");
	}

	public void setScene(Scene scene) {
		this.scene = scene;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public void setStageAndScene(Stage stage, Scene scene) {
		this.stage = stage;
		this.scene = scene;
	}
}
