package CookBookView.listview;

import java.io.IOException;
import java.util.LinkedList;

import CookBookDataBaseAcess.DatabaselayerObject;
import CookBookEntity.Recipe;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class ListviewController {
	@FXML
	private ImageView vegen;
	@FXML
	private ImageView egg_milk;
	@FXML
	private ImageView meat;
	@FXML
	private Text Recipename;
	@FXML
	private Label favourite;
	@FXML
	private VBox vbox;
	private Stage stage;
	private Scene scene;
	private DatabaselayerObject databaselayerObject;

	// Event Listener on ImageView[#vegen].onDragDetected
	@FXML
	public void showVegen(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#egg_milk].onDragDetected
	@FXML
	public void showEgg_Mlik(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#meat].onDragDetected
	@FXML
	public void showMeat(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Text[#Recipename].onDragDetected
	@FXML
	public void showRecipename(MouseEvent event) {
		// TODO Autogenerated
	}

	public void createSearchedRecipeSubview(TextField searcher) throws IOException {
		LinkedList<Recipe> list = databaselayerObject.showsearchingrecipelist(searcher.getText());
		for (int i = 1; i <= list.size(); i++) {
			Recipe recipe = list.get(i - 1);
			FXMLLoader loader = new FXMLLoader(getClass().getResource("subview.fxml"));
			Pane subView = loader.load();
			SubviewController controller = loader.getController();
			controller.setRecipe(recipe);
			controller.setStageAndScene(stage, scene);
			controller.setDatabaselayerObject(databaselayerObject);
			controller.setStar(recipe.getRate());
			vbox.getChildren().add(subView);
		}
	}

	public void createAllRecipeSubView(TextField searcher) throws IOException {
		LinkedList<Recipe> list = databaselayerObject.getallrecipelist();
		for (int i = 1; i <= list.size(); i++) {
			Recipe recipe = list.get(i - 1);
			FXMLLoader loader = new FXMLLoader(getClass().getResource("subview.fxml"));
			Pane subView = loader.load();
			SubviewController controller = loader.getController();
			controller.setRecipe(recipe);
			controller.setStageAndScene(stage, scene);
			controller.setDatabaselayerObject(databaselayerObject);
			controller.setStar(recipe.getRate());
			vbox.getChildren().add(subView);
		}
	}

	public void createUserRecipeSubView(TextField seacher) throws IOException {
		LinkedList<Recipe> list = databaselayerObject.getallrecipelist();
		for (int i = 1; i <= list.size(); i++) {
			Recipe recipe = list.get(i - 1);
			FXMLLoader loader = new FXMLLoader(getClass().getResource("subview.fxml"));
			Pane subView = loader.load();
			SubviewController controller = loader.getController();
			controller.setRecipe(recipe);
			controller.setStageAndScene(stage, scene);
			controller.setDatabaselayerObject(databaselayerObject);
			controller.setStar(recipe.getRate());
			vbox.getChildren().add(subView);
		}
	}

	public void createUserFavouriteRecipeSubView(TextField seacher) throws IOException {
		//
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public void setScene(Scene scene) {
		this.scene = scene;
	}

	public void setStageAndScene(Stage stage, Scene scene) {
		this.stage = stage;
		this.scene = scene;
	}

	public void setDatabaselayerObject(DatabaselayerObject databaselayerObject) {
		this.databaselayerObject = databaselayerObject;
	}
}
