package CookBookView.listview;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class PaneController {
	@FXML
	private Text Recipename;
	@FXML
	private Label favourite;

	// Event Listener on Text[#Recipename].onDragDetected
	@FXML
	public void showRecipename(MouseEvent event) {
		// TODO Autogenerated
	}
}
