package CookBookView.createview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.security.KeyStore.PrivateKeyEntry;

import CookBookView.firstview.fvController;
import DigitalCookbook.CookBook;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class createpaneController {
	@FXML
	private TextArea recipename;
	@FXML
	private Label star5;
	@FXML
	private TextArea preparationTime;
	@FXML
	private TextArea Category;
	@FXML
	private TextArea Cooktime;
	@FXML
	private Label favourite;
	@FXML
	private Button logout;
	@FXML
	private Label user;
	@FXML
	private TextField servingperson;
	@FXML
	private Label ingredient;
	@FXML
	private Button cancel;
	@FXML
	private Pane mainPane;
	
	private ScrollPane subinpane ;
	
	private ScrollPane substpane ;
	
	private ScrollPane subcmpane;
	
	private boolean subsm = false;
	private boolean subin = false;
	private boolean subst = false;

	
	private CookBook cookbook;
	private Stage stage; 
	private Scene scene; 
	// Event Listener on Label[#favourite].onDragDetected
	@FXML
	public void choosetobeFavourite(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#logout].onAction
	@FXML
	public void logOut(ActionEvent event) throws Exception {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("../firstview/fv.fxml"));
		Parent root = loader.load();
		fvController controller = loader.getController();
		controller.setStageAndScene(stage, scene);
		scene.setRoot(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on TextField[#servingperson].onAction
	@FXML
	public void servingPerson(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void back(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void createRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void createIngredient(ActionEvent event) throws Exception {
		if(this.subin==false)
		{
		FXMLLoader loader = new FXMLLoader(getClass().getResource("inpane.fxml"));
		this.subinpane = (ScrollPane)loader.load();
		this.subin = true; 
		System.out.println("create ingredient");
		}
		System.out.println("create ingredient");
		this.mainPane.getChildren().add(this.subinpane);
	}
	// Event Listener on Button.onAction
	@FXML
	public void createSteps(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void createComment(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setStage(Stage stage) {
		this.stage = stage ;
	}
	
	public void setScene(Scene scene) {
		this.scene = scene ; 
	}
	
	public void setCookBook(CookBook cookbook) {
		this.cookbook = cookbook;
	}
}
