package CookBookView.createview;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class inpanehboxController {
	@FXML
	private TextField Name;
	@FXML
	private TextField Usage;
	@FXML
	private TextField Unit;
	@FXML
	private TextField Description;
	@FXML
	private Button delete;

	// Event Listener on Button[#delete].onAction
	@FXML
	public void deletenode(ActionEvent event) {
		// TODO Autogenerated
	}
}
