package CookBookView.createview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

public class inpaneController {
	@FXML
	private ImageView add;
	@FXML
	private VBox inpaneVBox;
	@FXML
	private Button confirm;

	// Event Listener on ImageView[#add].onDragDetected
	@FXML
	public void addIngredient() throws Exception{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("inpanehbox.fxml"));
		HBox hBox = loader.load();
		inpaneVBox.getChildren().add(hBox);
	}
}
