package CookBookView.createview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.util.LinkedList;

import javax.print.event.PrintServiceAttributeListener;

import CookBookEntity.PreparationStep;
import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

public class steppaneController {
	@FXML
	private VBox vbox;
	@FXML
	private ImageView add;
	
	private LinkedList<PreparationStep> pslist;
	
	// Event Listener on ImageView[#add].onDragDetected
	@FXML
	public void addLine(MouseEvent event) throws Exception {
		// TODO Autogenerated
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("stpanehbox.fxml"));
		HBox stHBox = (HBox) loader.load(); 
		this.vbox.getChildren().add(stHBox);
	}
	// Event Listener on Button[#confirm].onAction
	@FXML
	public void saveSteps(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public VBox getvbox() {
		return this.vbox ; 
	}
	
	public void setPreparationStepList(LinkedList<PreparationStep> preparationSteps)
	{
		this.pslist = preparationSteps;
	}
	
	public LinkedList<PreparationStep> getPreparationStepList(){
		return this.pslist; 
	}
	
}
