package CookBookView.editview;

import javafx.scene.control.TextArea;
import javafx.scene.control.ScrollPane;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import CookBookDataBaseAcess.DatabaselayerObject;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;
import javafx.stage.*;
import javafx.scene.*;
import CookBookEntity.Ingredient;
import CookBookEntity.Recipe;
import DigitalCookbook.CookBook;
public class editpaneController implements Initializable {
	@FXML
	private Label star5;
	@FXML
	private Label favourite;
	@FXML
	private Button logout;
	@FXML
	private Label user;
	@FXML
	private TextField servingperson;
	@FXML
	private Label ingredient;
	
	@FXML
	private Button cancel;
	private DatabaselayerObject dao;
	private Stage stage ;
	private Scene scene; 
	@FXML
	private TextArea recipename; 
	@FXML
	private TextArea preparationTime; 
	@FXML
	private TextArea Category;
	@FXML
	private Pane mainPane; 
	
	private ScrollPane subinPane;
	
	private ScrollPane substPane;
	// Event Listener on Label[#favourite].onDragDetected
	
	private Recipe recipe ;
	private CookBook cookbook ; 
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		this.subinPane = new ScrollPane();
		this.substPane = new ScrollPane();
	}
	@FXML
	public void choosetobeFavourite(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#logout].onAction
	@FXML
	public void logOut(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#servingperson].onAction
	@FXML
	public void servingPerson(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#ingredient].onDragDetected
	@FXML
	public void showIngredients(MouseEvent event) throws Exception {
		// TODO Autogenerated
		
		this.mainPane.getChildren().add(this.subinPane);
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void back(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setScene(Scene scene) {
		this.scene  = scene; 
		
	}
	public void setStage(Stage stage) {
		this.stage = stage ;
	}
	
	public void setDataBase(DatabaselayerObject database) {
		this.dao = database; 
		
	}
	public void createRecipe() {
		this.recipe = new Recipe() ; 
		recipe.setCategory(this.Category.getText());
		recipe.setPreparationTime(Integer.parseInt(this.preparationTime.getText()));
		recipe.setServeNumber(Integer.parseInt(this.servingperson.getText()));
		recipe.setName(this.recipename.getText());
		
		System.out.println(this.recipe.toString());
	}
	
	public void setCookBook(CookBook cookbook) {
		this.cookbook = cookbook ; 
	}
	
	public Recipe getRecipe() {
		return this.recipe; 
	}
	

}
