package CookBookView.loginview;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class loginController {
	@FXML
	private Button confirm;
	@FXML
	private TextField nameText;
	@FXML
	private Button clearpw;
	@FXML
	private Button clearun;
	@FXML
	private Button register;
	@FXML
	private PasswordField passwordText;
	
	

	// Event Listener on Button[#confirm].onAction
	@FXML
	public void checkNameAndPassword(ActionEvent event) throws IOException {
		
		GridPane root = (GridPane) FXMLLoader.load(getClass().getResource("tinywin/mini.fxml"));
        Scene scene = new Scene(root, 270, 160);
        Stage stage = new Stage();
        stage.setScene(scene);
		stage.show();
		// TODO Autogenerated
	}
	// Event Listener on Button[#clearpw].onAction
	@FXML
	public void clearPassword(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#clearun].onAction
	@FXML
	public void clearUserName(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#register].onAction
	@FXML
	public void backtoRegisterView(ActionEvent event) {
		// TODO Autogenerated
	}
}
